baseURL = "https://acgnm.github.io/techBlog"
languageCode = "en-us"
title = "Day Day Up"
theme = "hello-friend-ng"

logoText = "cd /home/zgong"
logoHomeLink = "/"

[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"