baseURL = "https://acgnm.github.io/techBlog"
languageCode = "en-us"
title = "Day Day Up"
theme = "hello-friend-ng"

logoHomeLink = "/techBlog"

[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"